name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

# This prevents multiple builds from running at the same time if you push twice
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      # This addresses the deprecation warning by forcing the runner to use Node 24
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # Bumping to 24 to match the runner environment
          node-version: 24
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm install
          
      - name: Build
        run:  CI=false npm run build -- --base=/idox-lifecycle/
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
